[package]
name = "synacor-vm"
version = "0.1.0"
authors = ["Purple Myst <PurpleMyst@users.noreply.github.com>"]
edition = "2018"

[dependencies]
colored = "1.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde-big-array = "0.3.1"
